custom v1

diff --git a/bin/moodle-docker-compose b/bin/moodle-docker-compose
--- a/bin/moodle-docker-compose
+++ b/bin/moodle-docker-compose
@@ -30,7 +30,7 @@ else
   dockercompose="docker-compose"
 fi
 dockercompose="${dockercompose} -f ${basedir}/base.yml"
-dockercompose="${dockercompose} -f ${basedir}/service.mail.yml"
+# dockercompose="${dockercompose} -f ${basedir}/service.mail.yml"
 
 # PHP Version.
 export MOODLE_DOCKER_PHP_VERSION=${MOODLE_DOCKER_PHP_VERSION:-8.1}
@@ -52,10 +52,10 @@ fi
 # Expose DB port if requested.
 if [[ $MOODLE_DOCKER_DB_PORT == *":"* ]] || [[ $MOODLE_DOCKER_DB_PORT -gt 0 ]]
 then
-    # If no bind ip has been configured (bind_ip:port), default to 127.0.0.1
+    # If no bind ip has been configured (bind_ip:port), default to 0.0.0.0
     if [[ ! $MOODLE_DOCKER_DB_PORT == *":"* ]]
     then
-        export MOODLE_DOCKER_DB_PORT=127.0.0.1:$MOODLE_DOCKER_DB_PORT
+        export MOODLE_DOCKER_DB_PORT=0.0.0.0:$MOODLE_DOCKER_DB_PORT
     fi
     filename="${basedir}/db.${MOODLE_DOCKER_DB}.port.yml"
     if [ -f $filename ];
@@ -65,154 +65,154 @@ then
 fi
 
 # Guess mobile app runtime
-if [ -z "$MOODLE_DOCKER_APP_RUNTIME" ];
-then
-    if [[ ! -z "$MOODLE_DOCKER_APP_PATH" ]];
-    then
-        appversion="$(cat $MOODLE_DOCKER_APP_PATH/package.json | sed -n -E 's/\s*"version": "([0-9]+\.[0-9]+\.[0-9]+)(.*)?",/\1/p')"
-    elif [[ ! -z "$MOODLE_DOCKER_APP_VERSION" ]];
-    then
-        appversion=$MOODLE_DOCKER_APP_VERSION
-    fi
+# if [ -z "$MOODLE_DOCKER_APP_RUNTIME" ];
+# then
+#     if [[ ! -z "$MOODLE_DOCKER_APP_PATH" ]];
+#     then
+#         appversion="$(cat $MOODLE_DOCKER_APP_PATH/package.json | sed -n -E 's/\s*"version": "([0-9]+\.[0-9]+\.[0-9]+)(.*)?",/\1/p')"
+#     elif [[ ! -z "$MOODLE_DOCKER_APP_VERSION" ]];
+#     then
+#         appversion=$MOODLE_DOCKER_APP_VERSION
+#     fi
 
-    if [[ ! -z $appversion ]];
-    then
-        if [[ ! -z "$(echo $appversion | sed -n -E 's/([0-9]+\.[0-9]+\.[0-9]+)/\1/p')" ]];
-        then
-            appmajorversion="$(echo $appversion | sed -n -E 's/([0-9]+)\.[0-9]+\.[0-9]+/\1/p')"
-            appminorversion="$(echo $appversion | sed -n -E 's/[0-9]+\.([0-9]+)\.[0-9]+/\1/p')"
+#     if [[ ! -z $appversion ]];
+#     then
+#         if [[ ! -z "$(echo $appversion | sed -n -E 's/([0-9]+\.[0-9]+\.[0-9]+)/\1/p')" ]];
+#         then
+#             appmajorversion="$(echo $appversion | sed -n -E 's/([0-9]+)\.[0-9]+\.[0-9]+/\1/p')"
+#             appminorversion="$(echo $appversion | sed -n -E 's/[0-9]+\.([0-9]+)\.[0-9]+/\1/p')"
 
-            if (( $appmajorversion > 4 || $appminorversion > 3));
-            then
-                export MOODLE_DOCKER_APP_RUNTIME="ionic7"
-            else
-                export MOODLE_DOCKER_APP_RUNTIME="ionic5"
-            fi
-        else
-            export MOODLE_DOCKER_APP_RUNTIME="ionic7"
-        fi
-    fi
-fi
+#             if (( $appmajorversion > 4 || $appminorversion > 3));
+#             then
+#                 export MOODLE_DOCKER_APP_RUNTIME="ionic7"
+#             else
+#                 export MOODLE_DOCKER_APP_RUNTIME="ionic5"
+#             fi
+#         else
+#             export MOODLE_DOCKER_APP_RUNTIME="ionic7"
+#         fi
+#     fi
+# fi
 
 # Guess mobile app node version (only for local app development)
-if [[ -z "$MOODLE_DOCKER_APP_NODE_VERSION" ]]  && [[ ! -z "$MOODLE_DOCKER_APP_PATH" ]];
-then
-    appnodeversion="$(cat $MOODLE_DOCKER_APP_PATH/.nvmrc | sed -E "s/v(([0-9]+\.?)+)/\1/" || true)"
+# if [[ -z "$MOODLE_DOCKER_APP_NODE_VERSION" ]]  && [[ ! -z "$MOODLE_DOCKER_APP_PATH" ]];
+# then
+#     appnodeversion="$(cat $MOODLE_DOCKER_APP_PATH/.nvmrc | sed -E "s/v(([0-9]+\.?)+)/\1/" || true)"
 
-    export MOODLE_DOCKER_APP_NODE_VERSION="$appnodeversion"
-fi
+#     export MOODLE_DOCKER_APP_NODE_VERSION="$appnodeversion"
+# fi
 
 # Guess mobile app port (only when using Docker app images)
-if [[ -z "$MOODLE_DOCKER_APP_PORT" ]] && [[ ! -z "$MOODLE_DOCKER_APP_VERSION" ]];
-then
-    if [[ "$MOODLE_DOCKER_APP_RUNTIME" = "ionic5" ]];
-    then
-        export MOODLE_DOCKER_APP_PORT="80"
-    else
-        export MOODLE_DOCKER_APP_PORT="443"
-    fi
-fi
+# if [[ -z "$MOODLE_DOCKER_APP_PORT" ]] && [[ ! -z "$MOODLE_DOCKER_APP_VERSION" ]];
+# then
+#     if [[ "$MOODLE_DOCKER_APP_RUNTIME" = "ionic5" ]];
+#     then
+#         export MOODLE_DOCKER_APP_PORT="80"
+#     else
+#         export MOODLE_DOCKER_APP_PORT="443"
+#     fi
+# fi
 
 # Guess mobile app protocol
-if [[ -z "$MOODLE_DOCKER_APP_PROTOCOL" ]];
-then
-    if [[ "$MOODLE_DOCKER_APP_RUNTIME" = "ionic5" ]];
-    then
-        export MOODLE_DOCKER_APP_PROTOCOL="http"
-    else
-        export MOODLE_DOCKER_APP_PROTOCOL="https"
-    fi
-fi
+# if [[ -z "$MOODLE_DOCKER_APP_PROTOCOL" ]];
+# then
+#     if [[ "$MOODLE_DOCKER_APP_RUNTIME" = "ionic5" ]];
+#     then
+#         export MOODLE_DOCKER_APP_PROTOCOL="http"
+#     else
+#         export MOODLE_DOCKER_APP_PROTOCOL="https"
+#     fi
+# fi
 
 # Selenium browser
-browserparts=(${MOODLE_DOCKER_BROWSER//:/ })
-export MOODLE_DOCKER_BROWSER_NAME=${browserparts[0]}
-export MOODLE_DOCKER_BROWSER_TAG=${browserparts[1]}
+# browserparts=(${MOODLE_DOCKER_BROWSER//:/ })
+# export MOODLE_DOCKER_BROWSER_NAME=${browserparts[0]}
+# export MOODLE_DOCKER_BROWSER_TAG=${browserparts[1]}
 
-if [[ -z "$MOODLE_DOCKER_BROWSER_NAME" ]];
-then
-    MOODLE_DOCKER_BROWSER_NAME=firefox
-fi
+# if [[ -z "$MOODLE_DOCKER_BROWSER_NAME" ]];
+# then
+#     MOODLE_DOCKER_BROWSER_NAME=firefox
+# fi
 
-if [[ -z "$MOODLE_DOCKER_BROWSER_TAG" ]];
-then
-    if [[ "$MOODLE_DOCKER_BROWSER_NAME" = "firefox" ]];
-    then
-        MOODLE_DOCKER_BROWSER_TAG=3
-    elif [[ "$MOODLE_DOCKER_BROWSER_NAME" = "chrome" ]];
-    then
-        if [[ "$MOODLE_DOCKER_APP_RUNTIME" = "ionic5" ]];
-        then
-            MOODLE_DOCKER_BROWSER_TAG=3
-        else
-            MOODLE_DOCKER_BROWSER_TAG="120.0"
-        fi
-    fi
-fi
+# if [[ -z "$MOODLE_DOCKER_BROWSER_TAG" ]];
+# then
+#     if [[ "$MOODLE_DOCKER_BROWSER_NAME" = "firefox" ]];
+#     then
+#         MOODLE_DOCKER_BROWSER_TAG=3
+#     elif [[ "$MOODLE_DOCKER_BROWSER_NAME" = "chrome" ]];
+#     then
+#         if [[ "$MOODLE_DOCKER_APP_RUNTIME" = "ionic5" ]];
+#         then
+#             MOODLE_DOCKER_BROWSER_TAG=3
+#         else
+#             MOODLE_DOCKER_BROWSER_TAG="120.0"
+#         fi
+#     fi
+# fi
 
 # Mobile app for development
-if [[ "$MOODLE_DOCKER_BROWSER_NAME" == "chrome" ]];
-then
-    if [[ ! -z "$MOODLE_DOCKER_APP_PATH" ]];
-    then
-        dockercompose="${dockercompose} -f ${basedir}/moodle-app-dev.yml"
-    elif [[ ! -z "$MOODLE_DOCKER_APP_VERSION" ]];
-    then
-        # Mobile app using a docker image
-        dockercompose="${dockercompose} -f ${basedir}/moodle-app.yml"
-    fi
-fi
+# if [[ "$MOODLE_DOCKER_BROWSER_NAME" == "chrome" ]];
+# then
+#     if [[ ! -z "$MOODLE_DOCKER_APP_PATH" ]];
+#     then
+#         dockercompose="${dockercompose} -f ${basedir}/moodle-app-dev.yml"
+#     elif [[ ! -z "$MOODLE_DOCKER_APP_VERSION" ]];
+#     then
+#         # Mobile app using a docker image
+#         dockercompose="${dockercompose} -f ${basedir}/moodle-app.yml"
+#     fi
+# fi
 
-if [[ "$MOODLE_DOCKER_BROWSER_NAME" != "firefox" ]];
-then
-    dockercompose="${dockercompose} -f ${basedir}/selenium.${MOODLE_DOCKER_BROWSER_NAME}.yml"
-fi
+# if [[ "$MOODLE_DOCKER_BROWSER_NAME" != "firefox" ]];
+# then
+#     dockercompose="${dockercompose} -f ${basedir}/selenium.${MOODLE_DOCKER_BROWSER_NAME}.yml"
+# fi
 
 # Selenium VNC port
-export MOODLE_DOCKER_SELENIUM_SUFFIX=""
-if [[ $MOODLE_DOCKER_SELENIUM_VNC_PORT == *":"* ]] || [[ $MOODLE_DOCKER_SELENIUM_VNC_PORT -gt 0 ]]
-then
-    if [[ $(echo $MOODLE_DOCKER_BROWSER_TAG | sed 's/[^0-9].*//g') -lt 4 ]]
-    then
-        export MOODLE_DOCKER_SELENIUM_SUFFIX="-debug"
-    fi
+# export MOODLE_DOCKER_SELENIUM_SUFFIX=""
+# if [[ $MOODLE_DOCKER_SELENIUM_VNC_PORT == *":"* ]] || [[ $MOODLE_DOCKER_SELENIUM_VNC_PORT -gt 0 ]]
+# then
+#     if [[ $(echo $MOODLE_DOCKER_BROWSER_TAG | sed 's/[^0-9].*//g') -lt 4 ]]
+#     then
+#         export MOODLE_DOCKER_SELENIUM_SUFFIX="-debug"
+#     fi
 
-    # If no bind ip has been configured (bind_ip:port), default to 127.0.0.1
-    if [[ ! $MOODLE_DOCKER_SELENIUM_VNC_PORT == *":"* ]]
-    then
-        MOODLE_DOCKER_SELENIUM_VNC_PORT=127.0.0.1:$MOODLE_DOCKER_SELENIUM_VNC_PORT
-    fi
-    dockercompose="${dockercompose} -f ${basedir}/selenium.debug.yml"
-fi
+#     # If no bind ip has been configured (bind_ip:port), default to 0.0.0.0
+#     if [[ ! $MOODLE_DOCKER_SELENIUM_VNC_PORT == *":"* ]]
+#     then
+#         MOODLE_DOCKER_SELENIUM_VNC_PORT=0.0.0.0:$MOODLE_DOCKER_SELENIUM_VNC_PORT
+#     fi
+#     dockercompose="${dockercompose} -f ${basedir}/selenium.debug.yml"
+# fi
 
 # External services
-if [[ ! -z "$MOODLE_DOCKER_PHPUNIT_EXTERNAL_SERVICES" ]];
-then
-    dockercompose="${dockercompose} -f ${basedir}/phpunit-external-services.yml"
-fi
+# if [[ ! -z "$MOODLE_DOCKER_PHPUNIT_EXTERNAL_SERVICES" ]];
+# then
+#     dockercompose="${dockercompose} -f ${basedir}/phpunit-external-services.yml"
+# fi
 
 # BBB Mock
-if [[ ! -z "$MOODLE_DOCKER_BBB_MOCK" ]];
-then
-    dockercompose="${dockercompose} -f ${basedir}/bbb-mock.yml"
-fi
+# if [[ ! -z "$MOODLE_DOCKER_BBB_MOCK" ]];
+# then
+#     dockercompose="${dockercompose} -f ${basedir}/bbb-mock.yml"
+# fi
 
 # Matrix Mock
-if [[ ! -z "$MOODLE_DOCKER_MATRIX_MOCK" ]];
-then
-    dockercompose="${dockercompose} -f ${basedir}/matrix-mock.yml"
-fi
+# if [[ ! -z "$MOODLE_DOCKER_MATRIX_MOCK" ]];
+# then
+#     dockercompose="${dockercompose} -f ${basedir}/matrix-mock.yml"
+# fi
 
 #  Faildump directory
-if [[ ! -z "$MOODLE_DOCKER_BEHAT_FAILDUMP" ]];
-then
-    if [ ! -d "$MOODLE_DOCKER_BEHAT_FAILDUMP" ];
-    then
-        echo 'Error: $MOODLE_DOCKER_BEHAT_FAILDUMP is not an existing directory'
-        exit 1
-    fi
-    dockercompose="${dockercompose} -f ${basedir}/behat-faildump.yml"
-fi
+# if [[ ! -z "$MOODLE_DOCKER_BEHAT_FAILDUMP" ]];
+# then
+#     if [ ! -d "$MOODLE_DOCKER_BEHAT_FAILDUMP" ];
+#     then
+#         echo 'Error: $MOODLE_DOCKER_BEHAT_FAILDUMP is not an existing directory'
+#         exit 1
+#     fi
+#     dockercompose="${dockercompose} -f ${basedir}/behat-faildump.yml"
+# fi
 
 # Webserver host
 export MOODLE_DOCKER_WEB_HOST=${MOODLE_DOCKER_WEB_HOST:-localhost}
@@ -221,10 +221,10 @@ export MOODLE_DOCKER_WEB_HOST=${MOODLE_DOCKER_WEB_HOST:-localhost}
 export MOODLE_DOCKER_WEB_PORT=${MOODLE_DOCKER_WEB_PORT:-8000}
 if [[ $MOODLE_DOCKER_WEB_PORT == *":"* ]] || [[ $MOODLE_DOCKER_WEB_PORT -gt 0 ]]
 then
-    # If no bind ip has been configured (bind_ip:port), default to 127.0.0.1
+    # If no bind ip has been configured (bind_ip:port), default to 0.0.0.0
     if [[ ! $MOODLE_DOCKER_WEB_PORT == *":"* ]]
     then
-        MOODLE_DOCKER_WEB_PORT=127.0.0.1:$MOODLE_DOCKER_WEB_PORT
+        MOODLE_DOCKER_WEB_PORT=0.0.0.0:$MOODLE_DOCKER_WEB_PORT
     fi
     dockercompose="${dockercompose} -f ${basedir}/webserver.port.yml"
 fi
